name: '🚀 Development Release'

on:
  push:
    branches:
      - develop

concurrency:
  group: version-release
  cancel-in-progress: false

env:
  X-GITHUB_ENVIRONMENT: &GITHUB_ENVIRONMENT actions

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    environment: *GITHUB_ENVIRONMENT
    outputs:
      tag-name: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - name: Checkout source code
        uses: golemfoundation/github-actions/octant/git-checkout-lfs@0.8.2
        with:
          fetch-depth: 0
          token: ${{ secrets.HOUSEKEEPER_TOKEN }}

      - name: Setup Node.js and Yarn
        uses: golemfoundation/github-actions/octant/node-yarn-setup@0.8.2
        with:
          npm-auth-token: ${{ secrets.HOUSEKEEPER_PAT_OCTANT_V2_PACKAGES }}

      - name: Configure git
        uses: golemfoundation/github-actions/octant/git-configure@0.8.2
        with:
          gpg-key-base64: ${{ secrets.HOUSEKEEPER_SIGNING_KEY_B64 }}
          gpg-key-id: ${{ vars.HOUSEKEEPER_SIGNING_KEY_ID }}

      - name: Create release
        id: release
        uses: golemfoundation/github-actions/octant/release-dev-tag@0.8.2
        with:
          github-token: ${{ secrets.HOUSEKEEPER_TOKEN }}

  publish-package:
    name: Publish package
    needs:
      - create-release
    runs-on: ubuntu-latest
    environment: *GITHUB_ENVIRONMENT
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout source code
        uses: golemfoundation/github-actions/octant/git-checkout-lfs@0.8.2
        with:
          ref: ${{ needs.create-release.outputs.tag-name }}

      - name: Setup Node.js and Yarn
        uses: golemfoundation/github-actions/octant/node-yarn-setup@0.8.2
        with:
          npm-auth-token: ${{ secrets.HOUSEKEEPER_PAT_OCTANT_V2_PACKAGES }}

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@908c540300062bd5a7e473851cdb4282204cee09 # v1.9.1

      - name: Install Forge dependencies
        run: forge soldeer install

      - name: Publish package
        uses: golemfoundation/github-actions/octant/package-publish@0.8.2
        with:
          build-command: 'yarn build'
          tag: develop
